---
services:

  opencloud:
    environment:
      # this is needed for setting the correct CSP header
      COLLABORA_DOMAIN: ${COLLABORA_DOMAIN:-collabora.opencloud.test}

  collabora:
    container_name: opencloud-collabora
    ports:
      - "9980:9980"
    image: collabora/code:25.04.7.1.1
    # release notes: https://www.collaboraonline.com/release-notes/
    networks:
      opencloud-net:
    environment:
      aliasgroup1: http://opencloud:9200
      DONT_GEN_SSL_CERT: "YES"
      extra_params: |
        --o:ssl.enable=${COLLABORA_SSL_ENABLE:-true} \
        --o:ssl.ssl_verification=${COLLABORA_SSL_VERIFICATION:-true} \
        --o:ssl.termination=true \
        --o:welcome.enable=false \
        --o:net.frame_ancestors=${OC_DOMAIN:-cloud.opencloud.test} \
        --o:net.lok_allow.host[14]=${OC_DOMAIN:-cloud.opencloud.test} \
        --o:home_mode.enable=${COLLABORA_HOME_MODE:-false} \
        --o:logging.disable_server_audit=true
      username: ${COLLABORA_ADMIN_USER:-admin}
      password: ${COLLABORA_ADMIN_PASSWORD:-admin}
    cap_add:
      - MKNOD
    volumes:
      # Mount local TrueType fonts so the container can use system fonts
      # (e.g. Microsoft fonts like Arial, Calibri, Cambria by installing the `ttf-mscorefonts-installer` package).
      - /usr/share/fonts/truetype:/usr/share/fonts/truetype/more:ro
      - /usr/share/fonts/truetype:/opt/cool/systemplate/usr/share/fonts/truetype/more:ro
    logging:
      driver: ${LOG_DRIVER:-local}
    restart: always
    entrypoint: [ '/bin/bash', '-c' ]
    command: [ 'coolconfig generate-proof-key && /start-collabora-online.sh' ]
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9980/hosting/discovery" ]
      interval: 15s
      timeout: 10s
      retries: 5
